services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/server
    volumes:
      - ./pages:/pages
    depends_on:
      - db
  db:
    image: "postgres:16.2-alpine3.19"
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=tempPassword
      - POSTGRES_USER=server
      - POSTGRES_DB=server
